### PR TITLE
add Helper role env and let helpers use !mute

### PR DESCRIPTION
**Pull request by mlvzk**

### CODE REVIEW

**Comment by elkowar** [comment]
Looks good (although linting errors)

**Comment by mlvzk** [comment]
@elkowar ignore the warning, isHelper will be useful later

**Review by elkowar — APPROVED** [review]
Well then, looks good!

**Comment by Tanish2002** [comment]
@mlvzk I think you didn't change `!help` to show moderator commands(mute, etc) to helpers role.

**Pull request merged**
