### PR TITLE
Capitalize The Second "P" in "Display protocol"

### PR DESCRIPTION
**Pull request by co1ncidence**
This just looks a bit off to me considering how every other word is capitalized.

### CODE REVIEW

**Comment by buffet** [comment]
You have to change commands/fetch.go line 43 as well, otherwise you can't setfetch.

**Comment by co1ncidence** [comment]
Done. A second PR has been made fixing this in `fetch.go` as well.

**Comment by jaydenramm** [comment]
The capitalization rules for titles of books, movies, and other works vary a little between style guides. In general, you should capitalize the first word, all nouns, all verbs (even short ones, like is), all adjectives, and all proper nouns. That means you should lowercase articles, conjunctions, and prepositions—however, some style guides say to capitalize conjunctions and prepositions that are longer than five letters.

**Comment by 6gk** [comment]
this will also make buffer have to change the database to reflect this change

**Comment by buffet** [comment]
No, it won't. The database stores a JSON Object with DisplayProtocol as the key.

**Comment by 6gk** [comment]
sorry i r idot

**Pull request closed without merging**
