### PR TITLE
Make trup send a PSA

### LINKED ISSUE #156: Make trup send a PSA about repetitive posts whenever someone posts in #server-feedback
image

### PR DESCRIPTION
**Pull request by Tanish2002**
fixes #156
code is very shitty :")

### CODE REVIEW

**Comment by eepykate** [comment]
> Before posting, please make sure to check if your idea is a repetitive topic.  (Listed in pins)
> Note that we have added a consequence for failure.  The inability to delete repetitive feedback will result in an 'unsatisfactory' mark on your official testing record, followed by death.  Good luck!

**Comment by eepykate** [comment]
btw that message was a half joke

i really like GLaDOS' quotes, but if they don't get the reference it will make us look like dictators ~~which we try not to appear as publicly~~

**Comment by eepykate** [comment]
bumping since i dont recall too much discussion.
@buffet @elkowar

**Comment by eepykate** [comment]
@willeccles @JavaCafe01 @mlvzk 

not sure why i didn't ping you in the last comment but :shrug:.

**Comment by eepykate** [comment]
very important change.

**Comment by Tanish2002** [comment]
ok it work now plox review kthx.

**Comment by mlvzk** [comment]
Thanks

**Pull request merged**
