### PR TITLE
Capitalize Display Protocol

### PR DESCRIPTION
**Pull request by co1ncidence**
Sorry I closed the other PR's because I didn't want to make one for each change so i just fork and staged them all at once. 

My bad once again.

P.S. Credit goes to Weetbix for $TERM fix

### CODE REVIEW

**Comment by exorcist-git** [comment]
$term should not have a space in front

**Comment by exorcist-git** [comment]
it should be Terminal:$term

**Comment by co1ncidence** [comment]
Ah I understand what you mean, I had thought that `$TERM` was defined literally and the space not accounted for, my bad once again.

**Comment by co1ncidence** [comment]
Changes to `$TERM` have been reverted. o_O

**Comment by co1ncidence** [comment]
:weary:

**Pull request closed without merging**
