### PR TITLE
Add support for bars and resolution in fetch

### PR DESCRIPTION
**Pull request by eepykate**
also capitalize the p in `Display Protocol`

### CODE REVIEW

**Comment by buffet** [comment]
LGTM

**Comment by chxp82q** [comment]
@6gk `wibar` is part of `awesomewm`, it is not a binary. I believe you can just assume that if the wm is `awesomewm` then they use wibar, as no one would have the mind to use `polybar` on `awesomewm`.

**Comment by eepykate** [comment]
@JavaCafe01 dude you were the one who told me to add wibar...

**Comment by chxp82q** [comment]
@6gk ya but then after I was like "hold up..."

**Comment by chxp82q** [comment]
Wait when I ment assume I ment just output wibar if the fetch detects awesomewm

**Comment by eepykate** [comment]
Yeah I know what you meant, but I'm not going to do that.

**Comment by eepykate** [comment]
putting that one in this pr due to affecting what I added too

**Pull request merged**
