### PR TITLE
Don't pipe curl into bash

### PR DESCRIPTION
**Pull request by DRG-developer**
Just a small change in the !setfetch help.

### CODE REVIEW

**Comment by eepykate** [comment]
needlessly complicated

**Comment by exorcist365** [comment]
bruh fix title typo

**Comment by aosync** [comment]
> This fixes nothing.  
\- dylanaraps

**Comment by exorcist365** [comment]
hahaha

**Comment by ghost** [comment]
Don't break what already works. 😔

**Comment by exorcist365** [comment]
dude
the word is

recommended

**Pull request closed without merging**
