### PR TITLE
add gnome-terminal

### PR DESCRIPTION
**Pull request by quintenvandamme**
ikr

### CODE REVIEW

**Comment by eepykate** [comment]
Hi,
Have you tested this before & after?
Because line 133/134 (current/yours) should cover gnome-terminal and other
DE terminals that end with `-terminal`.

>

**Comment by quintenvandamme** [comment]
i have tested this many times but it never detected gnome-terminal

**Comment by eepykate** [comment]
sounds like user error to me.

image

**Comment by eepykate** [comment]
wait it didn't even run the sleep script lmao

```Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached```
was printed to the terminal a few seconds after

**Comment by quintenvandamme** [comment]
didn't happen with me

**Comment by eepykate** [comment]
i said user error

**Comment by eepykate** [comment]
wait, do you mean the error or the `ps | grep` thing?

**Comment by eepykate** [comment]
Apparently gnome is just an asshole and needs it's own rule for no reason??

**Pull request merged**
